modLoader="javafml" #mandatory
loaderVersion="[31,)"
issueTrackerURL="https://github.com/JaredR6/HealthScoring" #optional
logoFile="HS.png"
authors="PK_Anti"
license="MIT"

[[mods]]
modId="healthscoring"
displayName="Health Scoring"
version="${version}"
description='Mantle heart renderer for the tab display.'

[[dependencies.healthscoring]]
    modId="mantle"
    mandatory=true
    versionRange="[${mantleversion},)"
    ordering="AFTER"
    side="CLIENT"