modLoader="javafml" #mandatory
loaderVersion="[31,)"
issueTrackerURL="https://github.com/JaredR6/HealthScoring" #optional
logoFile="HS.png"
authors="PK_Anti"
license="MIT"

[[mods]]
modId="healthscoring"
displayName="Health Scoring"
version="${version}"
description='Advanced heart renderer for the tab display.'